### ISSUE TITLE
Errors while installing requests

### ISSUE THREAD

**Issue by mastercomp000** [Kenshii/500px-Bot#24]
![errors](https://user-images.githubusercontent.com/29845061/27773887-f8b59550-5f8c-11e7-874a-850639e9056f.jpg)

**Comment by mastercomp000** [comment]
![errors_1](https://user-images.githubusercontent.com/29845061/27773907-975a147e-5f8d-11e7-861a-64942625c439.jpg)

**Comment by shane-tw** [comment]
This isn't an issue with the script itself, so it really shouldn't be here.

However, it looks like your issue here is that the user you're logged in as doesn't have write permissions to /usr/lib/python3.4 so you'll need to use chmod or chown to solve this. You can probably find a copy-paste solution to the issue by googling the permission denied error.
